### ISSUE TITLE
Raspian 12 Value Error

### ISSUE THREAD

**Issue by apollo40** [hjelev/rpi-mqtt-monitor#102]
When i try to let the the rpi-cpu2mqqt.py run i get the following error:

Traceback (most recent call last):
  File "/root/rpi-mqtt-monitor/src/rpi-cpu2mqtt.py", line 730, in <module>
    gather_and_send_info()
  File "/root/rpi-mqtt-monitor/src/rpi-cpu2mqtt.py", line 630, in gather_and_send_info
    cpu_load, cpu_temp, used_space, voltage, sys_clock_speed, swap, memory, uptime_days, uptime_seconds, wifi_signal, wifi_signal_dbm, rpi5_fan_speed = collect_monitored_values()
                                                                                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/rpi-mqtt-monitor/src/rpi-cpu2mqtt.py", line 613, in collect_monitored_values
    memory = check_memory()
             ^^^^^^^^^^^^^^
  File "/root/rpi-mqtt-monitor/src/rpi-cpu2mqtt.py", line 84, in check_memory
    memory = round(float(memory.decode("utf-8").replace(",", ".")))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: ''

**Comment by hjelev** [comment]
duplicate issue
